### PR TITLE
Fix #1981: Ensure correctness of TDCU

### LINKED ISSUE #1970: async state-machine struct fields not populated when decompiling to C# 7.0 or later (ILSpy 6.0.0.5559-preview2)
(I searched existing issues for "async" and "state machine" and didn't find anything relevant).

I'm disassembling a .NET Framework 4.x assembly (I don't have the C# source code) that is disassembled like this when using ILSpy 4.x or when using ILSpy `6.0.0.5559-preview2` (provided "**C# 6.0 / VS 2015**" is selected in the toolbar):

```
[AsyncStateMachine(typeof(<FoobarAsync>d__7<>))]
public static Task<T> FoobarAsync<T>( string x, int y, Baz z = null )
{
    <FoobarAsync>d__7<T> stateMachine = default(<FoobarAsync>d__7<T>);
    stateMachine.x = x;
    stateMachine.y = y;
    stateMachine.z = z;
    stateMachine.<>t__builder = AsyncTaskMethodBuilder<T>.Create();
    stateMachine.<>1__state = -1;
    AsyncTaskMethodBuilder<T> <>t__builder = stateMachine.<>t__builder;
    <>t__builder.Start(ref stateMachine);
    return stateMachine.<>t__builder.Task;
}
```

However when decompiled in ILSpy `6.0.0.5559-preview2` with C# 7.0 or later (7.0, 7.1, 7.2, 7.3, and 8.0) selected, the struct population is omitted entirely and replaced with `num = -1`, giving only this:

```
[AsyncStateMachine(typeof(<FoobarAsync>d__7<>))]
public static Task<T> FoobarAsync<T>( string x, int y, Baz z = null )
{
    AsyncTaskMethodBuilder<T> asyncTaskMethodBuilder = AsyncTaskMethodBuilder<T>.Create();
    int num = -1;
    AsyncTaskMethodBuilder<T> asyncTaskMethodBuilder2 = asyncTaskMethodBuilder;
    <FoobarAsync>d__7<T> stateMachine = default(<FoobarAsync>d__7<T>);
    asyncTaskMethodBuilder2.Start(ref stateMachine);
    return asyncTaskMethodBuilder.Task;
}
```

I have some non-default settings, though I don't think they're relevant:

* View > [x] "Show all types and members"
* View > Options > Decompiler > [x] "Always show enum member values"
* View > Options > Misc > [x] "Allow multiple instances"

### LINKED ISSUE #1981: Ensure correctness of TDCU
Ensure correctness of `TransformDisplayClassUsage` by correctly implementing general "scalar replacement of aggregates" and then making it less aggressive by ensuring it only eliminates compiler-generated code.

### LINKED ISSUE #2002: Error decompiling @060002FA AssetResolver.LoadAssetAsType
Error decompiling @060002FA AssetResolver.LoadAssetAsType
in assembly "assets\bin\Data\Managed\Assembly-CSharp.dll"
 ---> System.NullReferenceException: 未将对象引用设置到对象的实例。
   at ICSharpCode.Decompiler.IL.Transforms.TransformDisplayClassUsage.VisitStObj(StObj inst) in offset 250
   at ICSharpCode.Decompiler.IL.Transforms.TransformDisplayClassUsage.Default(ILInstruction inst) in offset 25
   at ICSharpCode.Decompiler.IL.Transforms.TransformDisplayClassUsage.Default(ILInstruction inst) in offset 25
   at ICSharpCode.Decompiler.IL.Transforms.TransformDisplayClassUsage.Default(ILInstruction inst) in offset 25
   at ICSharpCode.Decompiler.IL.Transforms.TransformDisplayClassUsage.Default(ILInstruction inst) in offset 25
   at ICSharpCode.Decompiler.IL.Transforms.TransformDisplayClassUsage.Default(ILInstruction inst) in offset 25
   at ICSharpCode.Decompiler.IL.Transforms.TransformDisplayClassUsage.Default(ILInstruction inst) in offset 25
   at ICSharpCode.Decompiler.IL.Transforms.TransformDisplayClassUsage.Default(ILInstruction inst) in offset 25
   at ICSharpCode.Decompiler.IL.Transforms.TransformDisplayClassUsage.Default(ILInstruction inst) in offset 25
   at ICSharpCode.Decompiler.IL.Transforms.TransformDisplayClassUsage.Default(ILInstruction inst) in offset 25
   at ICSharpCode.Decompiler.IL.Transforms.TransformDisplayClassUsage.Default(ILInstruction inst) in offset 25
   at ICSharpCode.Decompiler.IL.Transforms.TransformDisplayClassUsage.Default(ILInstruction inst) in offset 25
   at ICSharpCode.Decompiler.IL.Transforms.TransformDisplayClassUsage.Default(ILInstruction inst) in offset 25
   at ICSharpCode.Decompiler.IL.Transforms.TransformDisplayClassUsage.Default(ILInstruction inst) in offset 25
   at ICSharpCode.Decompiler.IL.Transforms.TransformDisplayClassUsage.Run(ILFunction function, ILTransformContext context) in offset 435
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in offset 534
-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in offset 957
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(IMethod method, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in offset 191
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(ITypeDefinition typeDef, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in offset 643
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompileTypes(IEnumerable`1 types, DecompileRun decompileRun, ITypeResolveContext decompilationContext, SyntaxTree syntaxTree) in offset 171
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(IEnumerable`1 types) in offset 182
   at ICSharpCode.Decompiler.CSharp.WholeProjectDecompiler.<>c__DisplayClass38_0.<WriteCodeFilesInProject>b__2(IGrouping`2 file) in offset 46
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1() in offset 589
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask) in offset 6
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>) in offset 134

ILSpy版本  5.0.2.5153

6.0.0.5671-preview3，4.0.1.4530 也有同样的问题。

### PR DESCRIPTION
**Pull request by siegfriedpammer**
* [x] Fix #1981 
* [x] Fix #1970
* [x] Fix #2002

### CODE REVIEW

File: ICSharpCode.Decompiler/IL/Instructions/ILFunction.cs [hunk 1]
```diff
@@ -73,6 +73,12 @@ partial class ILFunction
 		/// </summary>
 		public BlockContainer DeclarationScope { get; internal set; }
 
+		/// <summary>
+		/// Gets the set of captured variables by this ILFunction.
+		/// </summary>
+		/// <remarks>This is populated by the <see cref="TransformDisplayClassUsage" /> step.</remarks>
+		public HashSet<ILVariable> CapturedVariables { get; } = new HashSet<ILVariable>(ILVariableEqualityComparer.Instance);
```
Comment (dgrunwald) [inline ICSharpCode.Decompiler/IL/Instructions/ILFunction.cs:80]: For the most part the ILAst is comparing `ILVariable`s by reference.
`ILVariableEqualityComparer` is only when you want different parts of a split variable to compare equal to another.

**Comment by dgrunwald** [comment]
I don't think this achieves what it was supposed to achieve -- the "copy propagation" aspect of the new TDCU is very ad-hoc and is highly unlikely to preserve program semantics in all cases.

I've just added a few new test cases and bugfix that fixes some of them.
