### PR TITLE
Fix #3402: System.NullReferenceException on right click on .NET 9

### LINKED ISSUE #3402: System.NullReferenceException on right click on .NET 9
### Steps to reproduce
See attached video:
1. Left click on `Action` (node A)
2. Left click on decompiled code
3. Right click on `Action<T>` (node B, anything but node A)
4. Right click on `Action` (anything but node B)

### Error message shown

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Linq.Enumerable.ArrayWhereIterator`1.ToArray(ReadOnlySpan`1 source, Func`2 predicate)
   at System.Linq.Enumerable.ListWhereIterator`1.ToArray()
   at TomsToolbox.Essentials.WeakEventSource`1.Raise(Object sender, TEventArgs e)
   at ICSharpCode.ILSpy.ContextMenuProvider.<>c__DisplayClass23_0.<ShowContextMenu>g__ContextMenu_Closing|0(Object sender, EventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.Popup.OnClosed(EventArgs e)
   at System.Windows.Controls.Primitives.Popup.DestroyWindow()
   at System.Windows.Threading.DispatcherTimer.FireTick()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
https://github.com/user-attachments/assets/b35aca9e-1706-4771-8a98-44a08b4399a1

### Details
Product in use: ILSpy
ILSpy version 9.0.0.7889+e94eb917395e50c74ea363a79df3514538989daa
.NET version 9.0.2+80aa709f5d919c6814726788dc6dabe23e79e672

### PR DESCRIPTION
**Pull request by tom-englert**
Link to issue(s) this covers

### Problem
#3402: System.NullReferenceException on right click on .NET 9

### Solution
* Fixed in TomsToolbox

https://github.com/tom-englert/TomsToolbox/commit/31b9dd57974512ba3d27a17bc25a25f802d4cb34

### CODE REVIEW

File: ILSpy/AssemblyTree/AssemblyTreeModel.cs [hunk 1]
```diff
@@ -767,6 +767,7 @@ private void TreeView_SelectionChanged()
 				}
 				else
 				{
+					ContextMenuProvider.ContextMenuClosed -= ContextMenuClosed;
```
Comment (christophwille) [inline ILSpy/AssemblyTree/AssemblyTreeModel.cs:770]: Please add a short comment about the intent of the trick (to avoid anyone scratching their head years later on why or even worse actually removing something that looks out of place)

Comment (tom-englert) [reply ILSpy/AssemblyTree/AssemblyTreeModel.cs:770]: This is just a common pattern to avoid duplicate event registration and execution.
It is not the primary fix, only avoids side effects.
