### PR TITLE
Fix stack overflow exception in CSharpResolver

### LINKED ISSUE #3466: Stack overflow involving explicit conversions
### Steps to reproduce
1. Load the assembly into ILSpy.
2. Save the assembly code.

[Assembly-CSharp-firstpass.zip](https://github.com/user-attachments/files/20024950/Assembly-CSharp-firstpass.zip)

### Error message shown

```
Stack overflow.
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataTypeDefinition.get_DirectBaseTypes()
   at ICSharpCode.Decompiler.TypeSystem.Implementation.BaseTypeCollector.CollectBaseTypes(ICSharpCode.Decompiler.TypeSystem.IType)
   at ICSharpCode.Decompiler.TypeSystem.Implementation.BaseTypeCollector.CollectBaseTypes(ICSharpCode.Decompiler.TypeSystem.IType)
   at ICSharpCode.Decompiler.TypeSystem.TypeSystemExtensions.GetAllBaseTypes(ICSharpCode.Decompiler.TypeSystem.IType)
   at ICSharpCode.Decompiler.CSharp.Resolver.CSharpConversions.IsSubtypeOf(ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType, Int32)
   at ICSharpCode.Decompiler.CSharp.Resolver.CSharpConversions.ImplicitReferenceConversion(ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType, Int32)
   at ICSharpCode.Decompiler.CSharp.Resolver.CSharpConversions.StandardImplicitConversion(ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType, Boolean)
   at ICSharpCode.Decompiler.CSharp.Resolver.CSharpConversions.StandardImplicitConversion(ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType)
   at ICSharpCode.Decompiler.CSharp.Resolver.CSharpConversions.IsEncompassingOrEncompassedBy(ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType)
   at ICSharpCode.Decompiler.CSharp.Resolver.CSharpConversions.GetApplicableConversionOperators(ICSharpCode.Decompiler.Semantics.ResolveResult, ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType, Boolean)
   at ICSharpCode.Decompiler.CSharp.Resolver.CSharpConversions.UserDefinedExplicitConversion(ICSharpCode.Decompiler.Semantics.ResolveResult, ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType)
   at ICSharpCode.Decompiler.CSharp.Resolver.CSharpConversions.ExplicitConversion(ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType)
   at ICSharpCode.Decompiler.CSharp.Resolver.CSharpConversions.SelectOperator(ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType, System.Collections.Generic.IList`1<OperatorInfo>, Boolean, ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType)
   at ICSharpCode.Decompiler.CSharp.Resolver.CSharpConversions.UserDefinedExplicitConversion(ICSharpCode.Decompiler.Semantics.ResolveResult, ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType)
   at ICSharpCode.Decompiler.CSharp.Resolver.CSharpConversions.ExplicitConversion(ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType)
   at ICSharpCode.Decompiler.CSharp.Resolver.CSharpConversions.SelectOperator(ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType, System.Collections.Generic.IList`1<OperatorInfo>, Boolean, ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType)
   at ICSharpCode.Decompiler.CSharp.Resolver.CSharpConversions.UserDefinedExplicitConversion(ICSharpCode.Decompiler.Semantics.ResolveResult, ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType)
   at ICSharpCode.Decompiler.CSharp.Resolver.CSharpConversions.ExplicitConversion(ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType)
   at ICSharpCode.Decompiler.CSharp.Resolver.CSharpConversions.SelectOperator(ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType, System.Collections.Generic.IList`1<OperatorInfo>, Boolean, ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType)
   at ICSharpCode.Decompiler.CSharp.Resolver.CSharpConversions.UserDefinedExplicitConversion(ICSharpCode.Decompiler.Semantics.ResolveResult, ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType)
   at ICSharpCode.Decompiler.CSharp.Resolver.CSharpConversions.ExplicitConversion(ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType)
   at ICSharpCode.Decompiler.CSharp.Resolver.CSharpConversions.SelectOperator(ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType, System.Collections.Generic.IList`1<OperatorInfo>, Boolean, ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType)
   at ICSharpCode.Decompiler.CSharp.Resolver.CSharpConversions.UserDefinedExplicitConversion(ICSharpCode.Decompiler.Semantics.ResolveResult, ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType)
   at ICSharpCode.Decompiler.CSharp.Resolver.CSharpConversions.ExplicitConversion(ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType)
   at ICSharpCode.Decompiler.CSharp.Resolver.CSharpConversions.SelectOperator(ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType, System.Collections.Generic.IList`1<OperatorInfo>, Boolean, ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType)
   at ICSharpCode.Decompiler.CSharp.Resolver.CSharpConversions.UserDefinedExplicitConversion(ICSharpCode.Decompiler.Semantics.ResolveResult, ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType)
   at ICSharpCode.Decompiler.CSharp.Resolver.CSharpConversions.ExplicitConversion(ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType)
   at ICSharpCode.Decompiler.CSharp.Resolver.CSharpConversions.SelectOperator(ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType, System.Collections.Generic.IList`1<OperatorInfo>, Boolean, ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType)
   at ICSharpCode.Decompiler.CSharp.Resolver.CSharpConversions.UserDefinedExplicitConversion(ICSharpCode.Decompiler.Semantics.ResolveResult, ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType)
   at ICSharpCode.Decompiler.CSharp.Resolver.CSharpConversions.ExplicitConversion(ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType)
   at ICSharpCode.Decompiler.CSharp.Resolver.CSharpConversions.SelectOperator(ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType, System.Collections.Generic.IList`1<OperatorInfo>, Boolean, ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType)
   at ICSharpCode.Decompiler.CSharp.Resolver.CSharpConversions.UserDefinedExplicitConversion(ICSharpCode.Decompiler.Semantics.ResolveResult, ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType)
   at ICSharpCode.Decompiler.CSharp.Resolver.CSharpConversions.ExplicitConversion(ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType)
   at ICSharpCode.Decompiler.CSharp.Resolver.CSharpConversions.SelectOperator(ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType, System.Collections.Generic.IList`1<OperatorInfo>, Boolean, ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType)
   at ICSharpCode.Decompiler.CSharp.Resolver.CSharpConversions.UserDefinedExplicitConversion(ICSharpCode.Decompiler.Semantics.ResolveResult, ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType)
   at ICSharpCode.Decompiler.CSharp.Resolver.CSharpConversions.ExplicitConversion(ICSharpCode.Decompiler.TypeSystem.IType, ICSharpCode.Decompiler.TypeSystem.IType)
...
```

### Details
* Product in use: e.g. ILSpy
* Version in use: latest commit (aff9649711fa3579f46e40336e7dc3fb8192302c)
* Any other relevant information to the issue, or your interest in contributing a fix.
  * I am currently investigating how this happened.

### PR DESCRIPTION
**Pull request by ds5678**
Resolves #3466 

### Solution
* Any comments on the approach taken, its consistency with surrounding code, etc.
* Which part of this PR is most in need of attention/improvement?
* [x] At least one test covering the code changed

### CODE REVIEW

File: ICSharpCode.Decompiler/CSharp/Resolver/CSharpResolver.cs [hunk 1]
```diff
@@ -805,7 +805,7 @@ public ResolveResult ResolveBinaryOperator(BinaryOperatorType op, ResolveResult
 					}
 					if (op == BinaryOperatorType.Equality || op == BinaryOperatorType.InEquality)
 					{
-						if (lhsType.IsReferenceType == true && rhsType.IsReferenceType == true
+						if (lhsType.IsReferenceType == true && rhsType.IsReferenceType == true && rhsType.Kind != TypeKind.Null
```
Comment (siegfriedpammer) [inline ICSharpCode.Decompiler/CSharp/Resolver/CSharpResolver.cs:808]: I would check both lhs and rhs...

**Comment by ds5678** [comment]
Is there anything else that needs done?

**Comment by siegfriedpammer** [comment]
sorry for the wait!

**Comment by ds5678** [comment]
Thanks for the merge!
