### PR TITLE
One single approach to using SHA*. Fixes #3673.

### LINKED ISSUE #3673: SHA1 Concurrency Exception (AssemblyReference.GetPublicKeyToken)
Sometimes when decompiling some of my dynamically-generated assemblies, I get a `CryptographicException` in `AssemblyReference.sha1.ComputeHash()`. As per a [StackOverflow Answer](https://stackoverflow.com/a/26592826), while static members of `HashAlgorithm` are thread-safe, instance members are not, so multiple threads trying to call `ComputeHash()` on the same instance at the same time will throw an exception.

This only seems to happen for some assemblies at random, but consistently (if it fails once, it'll always fail on that same assembly). I have no idea what about those assemblies causes it to fail in this way, whether it has anything to do with the assemblies being dynamically generated, or perhaps the assemblies are invalid in some particular way that doesn't have graceful handling, but it looks like it's a simple enough fix.

I propose either wrapping the `sha1.ComputeHash()` call (in `AssemblyReference.GetPublicKeyToken()` at `ICSharpCode.Decompiler/Metadata/AssemblyReference.cs:274`) in a `lock` clause, or defining `AssemblyReference.sha1` as a `ThreadLocal<SHA1>`.

### Steps to reproduce
1. `ilspycmd WaySharp.Protocol.Private.IKeyboardImpl.dll` 

### Error message shown
```
System.Security.Cryptography.CryptographicException: Concurrent operations from multiple threads on this type are not supported.
   at System.Security.Cryptography.ConcurrencyBlock.Enter(ConcurrencyBlock& block)
   at System.Security.Cryptography.HashProviderDispenser.EvpHashProvider.AppendHashData(ReadOnlySpan`1 data)
   at System.Security.Cryptography.HashProvider.AppendHashData(Byte[] data, Int32 offset, Int32 count)
   at System.Security.Cryptography.HashAlgorithm.ComputeHash(Byte[] buffer)
   at ICSharpCode.Decompiler.Metadata.AssemblyReference.GetPublicKeyToken() in /_/ICSharpCode.Decompiler/Metadata/AssemblyReferences.cs:line 274
   at ICSharpCode.Decompiler.Metadata.AssemblyReference.ICSharpCode.Decompiler.Metadata.IAssemblyReference.get_PublicKeyToken() in /_/ICSharpCode.Decompiler/Metadata/AssemblyReferences.cs:line 265
   at ICSharpCode.Decompiler.Metadata.UniversalAssemblyResolver.GetAssemblyInGac(IAssemblyReference reference) in /_/ICSharpCode.Decompiler/Metadata/UniversalAssemblyResolver.cs:line 687
   at ICSharpCode.Decompiler.Metadata.UniversalAssemblyResolver.ResolveInternal(IAssemblyReference name) in /_/ICSharpCode.Decompiler/Metadata/UniversalAssemblyResolver.cs:line 454
   at ICSharpCode.Decompiler.Metadata.UniversalAssemblyResolver.FindAssemblyFile(IAssemblyReference name) in /_/ICSharpCode.Decompiler/Metadata/UniversalAssemblyResolver.cs:line 298
   at ICSharpCode.Decompiler.Metadata.UniversalAssemblyResolver.Resolve(IAssemblyReference name) in /_/ICSharpCode.Decompiler/Metadata/UniversalAssemblyResolver.cs:line 215
   at ICSharpCode.Decompiler.Metadata.UniversalAssemblyResolver.<>c__DisplayClass22_0.<ResolveAsync>b__0() in /_/ICSharpCode.Decompiler/Metadata/UniversalAssemblyResolver.cs:line 257
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at ICSharpCode.Decompiler.TypeSystem.DecompilerTypeSystem.InitializeAsync(MetadataFile mainModule, IAssemblyResolver assemblyResolver, TypeSystemOptions typeSystemOptions) in /_/ICSharpCode.Decompiler/TypeSystem/DecompilerTypeSystem.cs:line 283
   at ICSharpCode.Decompiler.TypeSystem.DecompilerTypeSystem..ctor(MetadataFile mainModule, IAssemblyResolver assemblyResolver, TypeSystemOptions typeSystemOptions) in /_/ICSharpCode.Decompiler/TypeSystem/DecompilerTypeSystem.cs:line 235
   at ICSharpCode.Decompiler.TypeSystem.DecompilerTypeSystem..ctor(MetadataFile mainModule, IAssemblyResolver assemblyResolver, DecompilerSettings settings) in /_/ICSharpCode.Decompiler/TypeSystem/DecompilerTypeSystem.cs:line 225
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler..ctor(MetadataFile module, IAssemblyResolver assemblyResolver, DecompilerSettings settings) in /_/ICSharpCode.Decompiler/CSharp/CSharpDecompiler.cs:line 254
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler..ctor(String fileName, IAssemblyResolver assemblyResolver, DecompilerSettings settings) in /_/ICSharpCode.Decompiler/CSharp/CSharpDecompiler.cs:line 246
   at ICSharpCode.ILSpyCmd.ILSpyCmdProgram.GetDecompiler(String assemblyFileName) in D:\a\ILSpy\ILSpy\ICSharpCode.ILSpyCmd\IlspyCmdProgram.cs:line 345
   at ICSharpCode.ILSpyCmd.ILSpyCmdProgram.Decompile(String assemblyFileName, TextWriter output, String typeName) in D:\a\ILSpy\ILSpy\ICSharpCode.ILSpyCmd\IlspyCmdProgram.cs:line 390
   at ICSharpCode.ILSpyCmd.ILSpyCmdProgram.<OnExecuteAsync>g__PerformPerFileAction|83_0(String fileName, <>c__DisplayClass83_0&) in D:\a\ILSpy\ILSpy\ICSharpCode.ILSpyCmd\IlspyCmdProgram.cs:line 311
   at ICSharpCode.ILSpyCmd.ILSpyCmdProgram.OnExecuteAsync(CommandLineApplication app) in D:\a\ILSpy\ILSpy\ICSharpCode.ILSpyCmd\IlspyCmdProgram.cs:line 232
```

### Details
* ilspycmd 9.1.0.7988
* ICSharpCode.Decompiler 9.1.0.7988
* Fedora Linux 42 (6.18.13-100.fc42.x86_64)
* .NET Host 10.03
* .NET SDK 10.0.103
* .NET Runtimes 10.0.3, 9.0.13, 8.0.24

I'm using `ilspycmd` (along with `dotnet-il dasm` and `dotnet-ilverify`) to ensure my dynamically generated (`Reflection.Emit`ted) assemblies look like what I expect.

### PR DESCRIPTION
**Pull request by christophwille**
Additionally, now caches the token for repeating calls.

### CODE REVIEW

File: ICSharpCode.Decompiler/Metadata/AssemblyReferences.cs [hunk 1]
```diff
@@ -263,15 +263,32 @@ public string FullName {
...
+			if (value == null)
+			{
+				value = LazyInit.GetOrSet(ref publicKeyToken, ComputePublicKeyToken());
+			}
+			return value;
+		}
+
+		private byte[]? ComputePublicKeyToken()
 		{
 			if (entry.PublicKeyOrToken.IsNil)
```
Comment (siegfriedpammer) [inline ICSharpCode.Decompiler/Metadata/AssemblyReferences.cs]: this is now dead code?

Comment (siegfriedpammer) [reply ICSharpCode.Decompiler/Metadata/AssemblyReferences.cs]: why do we even bother with caching the result?

Comment (siegfriedpammer) [reply ICSharpCode.Decompiler/Metadata/AssemblyReferences.cs]: `GetPublicKeyToken` was implemented as a method in order to signal "this might be slow" as opposed to a property where the expectation is O(1).

**Comment by siegfriedpammer** [comment]
I think the fix of the bug is just local `SHA1.Create()` + `using`, no need to bother with caching/lazy init...
